id: jaco_robot_small_cube_0
pre_grasp_posture: 
  header: 
    seq: 0
    stamp: 0.000000000
    frame_id: 
  name[]
    name[0]: jaco_finger_joint_0
    name[1]: jaco_finger_joint_2
    name[2]: jaco_finger_joint_4
  position[]
    position[0]: 0.0045
    position[1]: 0.0045
    position[2]: 0.0045
  velocity[]
  effort[]
grasp_posture: 
  header: 
    seq: 0
    stamp: 0.000000000
    frame_id: 
  name[]
    name[0]: jaco_finger_joint_0
    name[1]: jaco_finger_joint_2
    name[2]: jaco_finger_joint_4
  position[]
    position[0]: -0.432062
    position[1]: -0.432062
    position[2]: -0.432062
  velocity[]
  effort[]
grasp_pose: 
  header: 
    seq: 0
    stamp: 0.000000000
    frame_id: 0
  pose: 
    position: 
      x: -0.0402668
      y: -0.0304912
      z: 0.185728
    orientation: 
      x: -0.36809
      y: -0.609471
      z: -0.514462
      w: 0.477894
grasp_quality: 32.3708
approach: 
  direction: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: 
    vector: 
      x: 0
      y: 0
      z: 0
  desired_distance: 0
  min_distance: 0
retreat: 
  direction: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: 
    vector: 
      x: 0
      y: 0
      z: 0
  desired_distance: 0
  min_distance: 0
max_contact_force: -1
allowed_touch_objects[]
