id: jaco_robot_small_cube_1
pre_grasp_posture: 
  header: 
    seq: 0
    stamp: 0.000000000
    frame_id: 
  name[]
    name[0]: jaco_finger_joint_0
    name[1]: jaco_finger_joint_2
    name[2]: jaco_finger_joint_4
  position[]
    position[0]: 0.0045
    position[1]: 0.0045
    position[2]: 0.0045
  velocity[]
  effort[]
grasp_posture: 
  header: 
    seq: 0
    stamp: 0.000000000
    frame_id: 
  name[]
    name[0]: jaco_finger_joint_0
    name[1]: jaco_finger_joint_2
    name[2]: jaco_finger_joint_4
  position[]
    position[0]: -0.443135
    position[1]: -0.443135
    position[2]: -0.443135
  velocity[]
  effort[]
grasp_pose: 
  header: 
    seq: 0
    stamp: 0.000000000
    frame_id: 0
  pose: 
    position: 
      x: -0.0335148
      y: -0.0364662
      z: 0.188197
    orientation: 
      x: -0.375924
      y: -0.584158
      z: -0.5217
      w: 0.495248
grasp_quality: 32.4071
approach: 
  direction: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: 
    vector: 
      x: 0
      y: 0
      z: 0
  desired_distance: 0
  min_distance: 0
retreat: 
  direction: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: 
    vector: 
      x: 0
      y: 0
      z: 0
  desired_distance: 0
  min_distance: 0
max_contact_force: -1
allowed_touch_objects[]
