id: jaco_robot_small_cube_0
pre_grasp_posture: 
  header: 
    seq: 0
    stamp: 0.000000000
    frame_id: 
  joint_names[]
    joint_names[0]: jaco_finger_joint_0
    joint_names[1]: jaco_finger_joint_2
    joint_names[2]: jaco_finger_joint_4
  points[]
    points[0]: 
        positions[]
        positions[0]: 0.0045
        positions[1]: 0.0045
        positions[2]: 0.0045
      velocities[]
      accelerations[]
      effort[]
      time_from_start: 0.000000000
grasp_posture: 
  header: 
    seq: 0
    stamp: 0.000000000
    frame_id: 
  joint_names[]
    joint_names[0]: jaco_finger_joint_0
    joint_names[1]: jaco_finger_joint_2
    joint_names[2]: jaco_finger_joint_4
  points[]
    points[0]: 
        positions[]
        positions[0]: -0.432062
        positions[1]: -0.432062
        positions[2]: -0.432062
      velocities[]
      accelerations[]
      effort[]
      time_from_start: 0.000000000
grasp_pose: 
  header: 
    seq: 0
    stamp: 0.000000000
    frame_id: 
  pose: 
    position: 
      x: -0.0402668
      y: -0.0304912
      z: 0.185728
    orientation: 
      x: -0.36809
      y: -0.609471
      z: -0.514462
      w: 0.477894
grasp_quality: 32.3708
pre_grasp_approach: 
  direction: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: 
    vector: 
      x: 0
      y: 0
      z: 0
  desired_distance: 0
  min_distance: 0
post_grasp_retreat: 
  direction: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: 
    vector: 
      x: 0
      y: 0
      z: 0
  desired_distance: 0
  min_distance: 0
post_place_retreat: 
  direction: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: 
    vector: 
      x: 0
      y: 0
      z: 0
  desired_distance: 0
  min_distance: 0
max_contact_force: -1
allowed_touch_objects[]
